# -*- coding: utf-8 -*-
"""Day_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/164nOBoUsa-c7XT8Ns3JSPW-Em1Fc_7CT
"""

lottery = "Hello coders"

print("Choose correct character of the word '",lottery,"' to win the lottery")

inputs = input(" ").lower()

if inputs == lottery[0] or inputs == lottery[1] or inputs == lottery[4] or inputs == lottery[6] or inputs == lottery[8]:
    print("Congratulations, You Win")
else:
    print("Sorry, You Lose! Better Luck Next Time")