# -*- coding: utf-8 -*-
"""Day_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaT_8Yr4MidSME65oS7aXtioGt2jCwwH
"""

x = input('Enter the values: ')
y = x.split()
print(y)

val = []

for i in y:
  val.append(int(i))

print(val)

SUM = sum(val)
print(SUM)