# -*- coding: utf-8 -*-
"""day_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwlurHBwGgF0xyk2SAvCzPU5zpvl6O-I
"""

marks = {
    "Maths" : "77",
    "English" : "86",
    "Hindi" : "97",
    "Science" : "82",
    "Social Science" : "70"
}
max_marks = max(marks,key=marks.get)
print(max_marks)