# -*- coding: utf-8 -*-
"""Day_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQNcVzkN-_fSpq0l11scsC2JjlCI2F4h
"""

def fun(n):
  return n % 3 == 0 and n % 5 == 0

li = list(range(1, 1001)) # list from range (1, 1000) 
print(list(filter (fun, li)))