# -*- coding: utf-8 -*-
"""day_06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMBc0JRiwEYH0gLlI9NfBzVWkLrw7TUV
"""

def decorators(fun):
	def deno(num1, num2):
		if num1 < num2 :
			num1, num2 = num2, num1
		return fun(num1, num2)
	return deno
	
@decorators
def div(num1, num2):
	return  num1 // num2

num1 =int(input("Enter the Number: "))
num2 =int(input("Enter the Number: "))
print(num1,num2)


print(div(num1, num2))