# -*- coding: utf-8 -*-
"""day_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Faa-s-dCO1iXK8VlDBoTMxx-kSWuM4_n
"""

n = int(input("Enter no. here : "))
def factorial_iter(n):
    product = 1
    for i in range(n):
        product = product * (i+1)
    return product

f = factorial_iter(n)
print(f)